/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ComputerShop.views;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;
import com.ComputerShop.views.CadastrarProduto;
import com.ComputerShop.views.PesquisaProduto;

/**
 *
 * @author diogo.sfelix
 */
public class Principall extends javax.swing.JFrame {

     CadastrarProduto menProdCadastro = null;
     PesquisaProduto menProdPesquisa = null;
     
     CadastroCliente menCliCadastro = null;
     PesquisaCliente menCliPesquisa = null;
     
     CadastrarVenda menVendProduto = null;
     RelatorioVenda menVendRelatorio = null;
    
    /**
     * Creates new form Principall
     */
    public Principall() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        desktop = new javax.swing.JDesktopPane(){

            private Image image;
            {
                try {
                    image = ImageIO.read(new File("src/com/ComputerShop/resources/fundo01.jpg"));

                } catch (Exception e){
                    e.printStackTrace();
                }

            }

            @Override
            protected void paintComponent(Graphics g){
                super.paintComponent(g);
                g.drawImage(image, 0, 0, getWidth(), getHeight(), this);
            }

        };
        menu = new javax.swing.JMenuBar();
        menCliente = new javax.swing.JMenu();
        menCliCad = new javax.swing.JMenuItem();
        menCliPesq = new javax.swing.JMenuItem();
        menProduto = new javax.swing.JMenu();
        menProdCad = new javax.swing.JMenuItem();
        menProdPesq = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 912, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 779, Short.MAX_VALUE)
        );

        menCliente.setText("Cliente");

        menCliCad.setText("Cadastro");
        menCliCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCliCadActionPerformed(evt);
            }
        });
        menCliente.add(menCliCad);

        menCliPesq.setText("Pesquisa");
        menCliPesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCliPesqActionPerformed(evt);
            }
        });
        menCliente.add(menCliPesq);

        menu.add(menCliente);

        menProduto.setText("Produto");

        menProdCad.setText("Cadastrar");
        menProdCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menProdCadActionPerformed(evt);
            }
        });
        menProduto.add(menProdCad);

        menProdPesq.setText("Pesquisar");
        menProdPesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menProdPesqActionPerformed(evt);
            }
        });
        menProduto.add(menProdPesq);

        menu.add(menProduto);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menProdCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menProdCadActionPerformed
        if (menProdCadastro == null || !menProdCadastro.isDisplayable()){
            menProdCadastro = new CadastrarProduto();
            desktop.add(menProdCadastro);
            this.openFrameInCenter(menProdCadastro);
        }
        menProdCadastro.toFront();
    }//GEN-LAST:event_menProdCadActionPerformed

    private void menProdPesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menProdPesqActionPerformed
        if (menProdPesquisa == null || !menProdPesquisa.isDisplayable()){
            menProdPesquisa = new PesquisaProduto();
            desktop.add(menProdPesquisa);
            this.openFrameInCenter(menProdPesquisa);
        }
        this.openFrameInCenter(menProdPesquisa);
        
    }//GEN-LAST:event_menProdPesqActionPerformed

    private void menCliCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCliCadActionPerformed
        if (menCliCadastro == null || !menCliCadastro.isDisplayable()){
            menCliCadastro = new CadastroCliente();
            desktop.add(menCliCadastro);
            this.openFrameInCenter(menCliCadastro);
        }
        this.openFrameInCenter(menCliCadastro);
    }//GEN-LAST:event_menCliCadActionPerformed

    private void menCliPesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCliPesqActionPerformed
        if (menCliPesquisa == null || !menCliPesquisa.isDisplayable()){
            menCliPesquisa = new PesquisaCliente();
            desktop.add(menCliPesquisa);
            this.openFrameInCenter(menCliPesquisa);
        }
        this.openFrameInCenter(menCliPesquisa);
    }//GEN-LAST:event_menCliPesqActionPerformed

    
    
    
    
        public void openFrameInCenter(JInternalFrame jif) {
            Dimension desktopSize = desktop.getSize();
            Dimension jInternalFrameSize = jif.getSize();
            int width = (desktopSize.width - jInternalFrameSize.width) / 2;
            int height = (desktopSize.height - jInternalFrameSize.height) / 2;
            jif.setLocation(width, height);
            jif.setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principall().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem menCliCad;
    private javax.swing.JMenuItem menCliPesq;
    private javax.swing.JMenu menCliente;
    private javax.swing.JMenuItem menProdCad;
    private javax.swing.JMenuItem menProdPesq;
    private javax.swing.JMenu menProduto;
    private javax.swing.JMenuBar menu;
    // End of variables declaration//GEN-END:variables
}
