/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ComputerShop.views;

/**
 *
 * @author diogo
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        Menu = new javax.swing.JMenuBar();
        MenCliente = new javax.swing.JMenu();
        MenCliCad = new javax.swing.JMenuItem();
        MenCliPesq = new javax.swing.JMenuItem();
        MenProduto = new javax.swing.JMenu();
        MenProdCad = new javax.swing.JMenuItem();
        MenProPesq = new javax.swing.JMenuItem();
        MenVendProd = new javax.swing.JMenu();
        MenVendVender = new javax.swing.JMenuItem();
        MenVendRel = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nome do Sistema");
        setResizable(false);

        MenCliente.setText("Cliente");

        MenCliCad.setText("Cadastrar ");
        MenCliCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenCliCadActionPerformed(evt);
            }
        });
        MenCliente.add(MenCliCad);

        MenCliPesq.setText("Pesquisar");
        MenCliPesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenCliPesqActionPerformed(evt);
            }
        });
        MenCliente.add(MenCliPesq);

        Menu.add(MenCliente);

        MenProduto.setText("Produto");

        MenProdCad.setText("Cadastrar");
        MenProdCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenProdCadActionPerformed(evt);
            }
        });
        MenProduto.add(MenProdCad);

        MenProPesq.setText("Pesquisa");
        MenProPesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenProPesqActionPerformed(evt);
            }
        });
        MenProduto.add(MenProPesq);

        Menu.add(MenProduto);

        MenVendProd.setText("Vendas");

        MenVendVender.setText("Vender Produto");
        MenVendVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenVendVenderActionPerformed(evt);
            }
        });
        MenVendProd.add(MenVendVender);

        MenVendRel.setText("Relatorio");
        MenVendRel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenVendRelActionPerformed(evt);
            }
        });
        MenVendProd.add(MenVendRel);

        Menu.add(MenVendProd);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 896, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 775, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MenCliCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenCliCadActionPerformed
        // TODO add your handling code here:
        CadastroCliente menCliCad = new CadastroCliente();
        menCliCad.setVisible(true);
        desktop.add(menCliCad);
        
    }//GEN-LAST:event_MenCliCadActionPerformed

    private void MenCliPesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenCliPesqActionPerformed
        // TODO add your handling code here:
        PesquisaCliente menCliPesq = new PesquisaCliente();
        menCliPesq.setVisible(true);
        desktop.add(menCliPesq);
        
    }//GEN-LAST:event_MenCliPesqActionPerformed

    private void MenProdCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenProdCadActionPerformed
        // TODO add your handling code here:
        CadastrarProduto menProdCad = new CadastrarProduto();
        menProdCad.setVisible(true);
        desktop.add(menProdCad);
        
    }//GEN-LAST:event_MenProdCadActionPerformed

    private void MenProPesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenProPesqActionPerformed
        // TODO add your handling code here:
        PesquisaProduto menProdPesq = new PesquisaProduto();
        menProdPesq.setVisible(true);
        desktop.add(menProdPesq);
        
    }//GEN-LAST:event_MenProPesqActionPerformed

    private void MenVendVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenVendVenderActionPerformed
        // TODO add your handling code here:
        CadastrarProduto menVendProd = new CadastrarProduto();
        menVendProd.setVisible(true);
        desktop.add(menVendProd);
        
    }//GEN-LAST:event_MenVendVenderActionPerformed

    private void MenVendRelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenVendRelActionPerformed
        // TODO add your handling code here:
        RelatorioVenda menVendRel = new RelatorioVenda();
        menVendRel.setVisible(true);
        //desktop.add(menVendRel);
        
    }//GEN-LAST:event_MenVendRelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenCliCad;
    private javax.swing.JMenuItem MenCliPesq;
    private javax.swing.JMenu MenCliente;
    private javax.swing.JMenuItem MenProPesq;
    private javax.swing.JMenuItem MenProdCad;
    private javax.swing.JMenu MenProduto;
    private javax.swing.JMenu MenVendProd;
    private javax.swing.JMenuItem MenVendRel;
    private javax.swing.JMenuItem MenVendVender;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JDesktopPane desktop;
    // End of variables declaration//GEN-END:variables
}
