/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ComputerShop.views;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.JInternalFrame;

/**
 *
 * @author ffreire
 */
public class TelaPrincipal extends javax.swing.JFrame {
  
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem5 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        desktop = new javax.swing.JDesktopPane() {
            private Image image;
            {
                try {
                    image = ImageIO.read(new File("src/resources/hotel.jpg"));
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }

            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.drawImage(image, 0, 0, getWidth(), getHeight(), this);
            }
        };
        jMenuBar1 = new javax.swing.JMenuBar();
        menCliente = new javax.swing.JMenu();
        menCliCad = new javax.swing.JMenuItem();
        menCliPesq = new javax.swing.JMenuItem();
        menProduto = new javax.swing.JMenu();
        menProPesq = new javax.swing.JMenuItem();
        menProdPesq = new javax.swing.JMenuItem();
        menVendas = new javax.swing.JMenu();
        menVendProduto = new javax.swing.JMenuItem();
        menVendRel = new javax.swing.JMenuItem();

        jMenuItem5.setText("jMenuItem5");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jMenuItem6.setText("jMenuItem6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BDAC - Sistemas");

        desktop.setDoubleBuffered(true);

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 995, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 766, Short.MAX_VALUE)
        );

        menCliente.setText("Cliente");
        menCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menClienteActionPerformed(evt);
            }
        });

        menCliCad.setText("Cadastrar Cliente");
        menCliCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCliCadActionPerformed(evt);
            }
        });
        menCliente.add(menCliCad);

        menCliPesq.setText("Consultar Clientes");
        menCliPesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCliPesqActionPerformed(evt);
            }
        });
        menCliente.add(menCliPesq);

        jMenuBar1.add(menCliente);

        menProduto.setText("Produto");

        menProPesq.setText("Cadastrar Produto");
        menProPesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menProPesqActionPerformed(evt);
            }
        });
        menProduto.add(menProPesq);

        menProdPesq.setText("Consultar Produtos");
        menProdPesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menProdPesqActionPerformed(evt);
            }
        });
        menProduto.add(menProdPesq);

        jMenuBar1.add(menProduto);

        menVendas.setText("Vendas");

        menVendProduto.setText("Efetuar um Pedido");
        menVendProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menVendProdutoActionPerformed(evt);
            }
        });
        menVendas.add(menVendProduto);

        menVendRel.setText("Gerar Relatório de Vendas");
        menVendRel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menVendRelActionPerformed(evt);
            }
        });
        menVendas.add(menVendRel);

        jMenuBar1.add(menVendas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(865, 575));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menCliCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCliCadActionPerformed
            CadastroCliente menCliCad = new CadastroCliente();
            menCliCad.setVisible(true);
            desktop.add(menCliCad);
    }//GEN-LAST:event_menCliCadActionPerformed

    private void menCliPesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCliPesqActionPerformed
            PesquisaCliente menCliPesq = new PesquisaCliente();
            menCliPesq.setVisible(true);
            desktop.add(menCliPesq);
    }//GEN-LAST:event_menCliPesqActionPerformed

    private void menProPesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menProPesqActionPerformed
            CadastrarProduto menProPesq = new CadastrarProduto();
            menProPesq.setVisible(true);
            desktop.add(menProPesq);
    }//GEN-LAST:event_menProPesqActionPerformed

    private void menProdPesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menProdPesqActionPerformed
            PesquisaProduto menProdPesq = new PesquisaProduto();
            menProdPesq.setVisible(true);
            desktop.add(menProdPesq);
    }//GEN-LAST:event_menProdPesqActionPerformed

    private void menVendProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menVendProdutoActionPerformed
            CadastrarVenda menVendProd = new CadastrarVenda();
            menVendProd.setVisible(true);
            desktop.add(menVendProd);
    }//GEN-LAST:event_menVendProdutoActionPerformed

    private void menVendRelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menVendRelActionPerformed
            RelatorioVenda menVendRel = new RelatorioVenda();
            menVendRel.setVisible(true);
            desktop.add(menVendRel);
    }//GEN-LAST:event_menVendRelActionPerformed

    private void menClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menClienteActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_menClienteActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JMenuItem menCliCad;
    private javax.swing.JMenuItem menCliPesq;
    private javax.swing.JMenu menCliente;
    private javax.swing.JMenuItem menProPesq;
    private javax.swing.JMenuItem menProdPesq;
    private javax.swing.JMenu menProduto;
    private javax.swing.JMenuItem menVendProduto;
    private javax.swing.JMenuItem menVendRel;
    private javax.swing.JMenu menVendas;
    // End of variables declaration//GEN-END:variables
}
